version: '3'

services:

  db:
    image: "postgres:9.6-alpine"
    container_name: db1
    restart: always

    ports:
      - 5432:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=f1_merch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata


  f1_merch:
    build: ./
    container_name: f1_merch
    volumes:
      - app-data
    environment:
      - DB_SERVER:db1
      - POSTGRES_DB=f1_merch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine

    depends_on:
      - db1



volumes:
  postgres_data:
